---
name: CPANPLUS-Dist-RPM
version: 0.0.2
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
abstract: a cpanplus backend to build RPM/RedHat rpms
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPANPLUS: 0
  CPANPLUS::Dist::Base: 0
  CPANPLUS::Error: 0
  Cwd: 0
  File::Basename: 0
  File::Copy: 0
  IPC::Cmd: 0
  POSIX: 0
  Pod::POM: 0
  Pod::POM::View::Text: 0
  Template: 0
  Text::Wrap: 0
  perl: 5.008
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  CPANPLUS::Dist::Fedora:
    file: lib/CPANPLUS/Dist/Fedora.pm
    version: 0.1.1
  CPANPLUS::Dist::RPM:
    file: lib/CPANPLUS/Dist/RPM.pm
    version: 0.0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
